# Generated by Django 3.2.6 on 2021-09-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helados', '0001_initial'),
        ('postres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helados.helados')),
                ('postre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postres.postres')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
